const commandsDatabase = [
    {
        id: "general-fun",
        title: "1.0 General & Fun",
        icon: "ph-house-line",
        tocLabel: "1.0 General & Fun",
        commands: [
            { name: "/serverinfo", desc: "Shows server information.", badge: "Everyone", type: "public" },
            { name: "/ping", desc: "Checks the bots latency.", badge: "Everyone", type: "public" },
            { name: "/prefix", desc: "View or change this server's text command prefix.", badge: "Manage Server", type: "perm" },
            { name: "/dashboard", desc: "Get a link to view server stats", badge: "Administrator", type: "perm" },
            { name: "/invite", desc: "Get the bot’s invite link.", badge: "Administrator", type: "perm" },
            { name: "/server avatar", desc: "View a member's avatar.", badge: "Everyone", type: "public" },
            { name: "/server count", desc: "View this server's member count.", badge: "Everyone", type: "public" },
            { name: "/server roleinfo", desc: "Get information about a role.", badge: "Everyone", type: "public" },
            { name: "/server roles", desc: "List server roles, a member's roles, or search role names.", badge: "Everyone", type: "public" },
            { name: "/server emojis", desc: "List server emojis or search by name.", badge: "Everyone", type: "public" },
            { name: "/server enlarge", desc: "Enlarge a custom emoji or role icon.", badge: "Everyone", type: "public" },
            { name: "/server invite", desc: "Get information about a Discord invite.", badge: "Everyone", type: "public" },
            { name: "/duel", desc: "Start a Battle Royale!", badge: "Everyone", type: "public" },
            { name: "/8ball", desc: "Ask the magic 8-ball a question.", badge: "Everyone", type: "public" },
            { name: "/discquote", desc: "Fake a discord screenshot.", badge: "Member", type: "role" },
            { name: "/cat says", desc: "Make a cat say something", badge: "Everyone", type: "public" },
            { name: "/remindme", desc: "Set a reminder for later", badge: "Everyone", type: "public" },
            { name: "/slap", desc: "Slap someone!", badge: "Everyone", type: "public" },
            { name: "/slap stats", desc: "View slap statistics", badge: "Everyone", type: "public" },
            { name: "/slap leaderboard", desc: "Top 10 most slapped users", badge: "Everyone", type: "public" }
        ]
    },

    {
        id: "moderation-core",
        title: "2.0 Core Moderation",
        icon: "ph-shield-checkered",
        tocLabel: "2.0 Moderation",
        commands: [
            { name: "/kick", desc: "Kicks user.", badge: "Kick", type: "perm" },
            { name: "/ban", desc: "Bans the user.", badge: "Ban", type: "perm" },
            { name: "/shadowban", desc: "Bans the user without being in the server.", badge: "Ban", type: "perm" },
            { name: "/unban", desc: "Unbans the user by ID.", badge: "Ban", type: "perm" },
            { name: "/untimeout", desc: "User can message and join VC again.", badge: "Moderate Member", type: "perm" },
            { name: "!mute", desc: "Prefix alias for timeout. Uses the existing timeout command logic.", badge: "Moderate Member", type: "perm" },
            { name: "!unmute", desc: "Prefix alias for untimeout. Uses the existing untimeout command logic.", badge: "Moderate Member", type: "perm" },
            { name: "/nick", desc: "Change a users Nickname.", badge: "Manage Nicknames", type: "perm" },
            { name: "/purge", desc: "Deletes x number of messages from that channel.", badge: "Manage Messages", type: "perm" },
            { name: "/staff clean", desc: "Deletes recent bot messages in the current channel.", badge: "Manage Messages", type: "perm" },
            { name: "/staff unlock", desc: "Unlocks a channel for everyone.", badge: "Manage Channels", type: "perm" },
            { name: "/staff locked", desc: "Lists channels currently locked for everyone.", badge: "Manage Channels", type: "perm" },
            { name: "/staff slowmode", desc: "Views, sets, or disables channel slowmode.", badge: "Manage Channels", type: "perm" },
            { name: "/staff members", desc: "Lists members who have a specific role.", badge: "Manage Server", type: "perm" },
            { name: "/staff timeouts", desc: "Lists currently timed-out members.", badge: "Moderate Member", type: "perm" },
            { name: "/staff logs", desc: "Shows a user's warning history.", badge: "Manage Messages", type: "perm" },
            { name: "/staff points", desc: "Shows a user's active warning count as moderation points.", badge: "Manage Messages", type: "perm" },
            { name: "/staff diagnose", desc: "Checks bot permissions and command prefix settings.", badge: "Manage Server", type: "perm" },
            { name: "/archive", desc: "Archive x amount of messages into a file and database.", badge: "Manage Message", type: "perm" },
            { name: "/archive_get", desc: "Lookup archive with archive ID.", badge: "Manage Message", type: "perm" },
            { name: "/warn add", desc: "Issue a warning to a member.", badge: "Manage Messages", type: "perm" },
            { name: "/warn list", desc: "List warnings registered to a user.", badge: "Manage Messages", type: "perm" },
            { name: "/warn clear", desc: "Clear all warnings from a user.", badge: "Manage Messages", type: "perm" },
            { name: "/softban", desc: "Kicks a member and deletes their messages from the last 1 to 7 days.", badge: "Ban", type: "perm" },
            { name: "/timeout", desc: "Prevents user from messaging and joining VC.", badge: "Moderate Member", type: "perm" },
            { name: "/purgetimeout", desc: "Timeout a member and sweep recent spam.", badge: "Moderate Member", type: "perm" },
            { name: "/lock", desc: "Locks or unlocks a channel for a role.", badge: "Manage Channels", type: "perm" }
        ]
    },

    {
        id: "server-administration",
        title: "2.1 Server Administration",
        icon: "ph-sliders",
        tocLabel: "2.1 Server Admin",
        commands: [
            { name: "/log list", desc: "List log types.", badge: "Manage Server", type: "perm" },
            { name: "/set_log_webhook", desc: "Set the webhook URL for logging events.", badge: "Manage Server", type: "perm" },
            { name: "/add_ignored_channel", desc: "Adds a channel to ignore list.", badge: "Manage Server", type: "perm" },
            { name: "/remove_ignored_channel", desc: "Remove a channel from ignore list.", badge: "Manage Server", type: "perm" },
            { name: "/list_ignored_channels", desc: "Shows a list of channels from ignore list.", badge: "Manage Server", type: "perm" },
            { name: "/quarantine", desc: "Quarantine a member (removes roles).", badge: "Kick", type: "perm" },
            { name: "/quarantine_remove", desc: "Restore a user from quarantine.", badge: "Administrator", type: "perm" },
            { name: "/activity setup", desc: "Opt-in to activity tracking or update threshold.", badge: "Manage Server", type: "perm" },
            { name: "/activity disable", desc: "Disable activity tracking for this server.", badge: "Manage Server", type: "perm" },
            { name: "/activity status", desc: "View current activity tracking configuration for this server.", badge: "Everyone", type: "public" },
            { name: "/activity refresh", desc: "Force update all activity roles immediately instead of waiting for the automatic cycle.", badge: "Manage Server", type: "perm" },
            { name: "/serveradmin addrole", desc: "Create a new server role.", badge: "Manage Roles", type: "perm" },
            { name: "/serveradmin delrole", desc: "Delete a server role.", badge: "Manage Roles", type: "perm" },
            { name: "/serveradmin editrole", desc: "Edit role name, color, hoist, or mentionable settings.", badge: "Manage Roles", type: "perm" },
            { name: "/serveradmin memberrole", desc: "Add, remove, or toggle a role for a member.", badge: "Manage Roles", type: "perm" },
            { name: "/serveradmin editchannel", desc: "Edit a text channel's name, topic, NSFW flag, or slowmode.", badge: "Manage Channels", type: "perm" },
            { name: "/serveradmin modules", desc: "List bot modules enabled for this server.", badge: "Manage Server", type: "perm" },
            { name: "/serveradmin module", desc: "Enable or disable a bot module for this server.", badge: "Manage Server", type: "perm" },
            { name: "/serveradmin mods", desc: "View roles with moderation permissions.", badge: "Manage Server", type: "perm" },
            { name: "/serveradmin say", desc: "Send a message as the bot.", badge: "Manage Messages", type: "perm" },
            { name: "/returning_role set", desc: "Configure the returning member role", badge: "Administrator", type: "perm" },
            { name: "/returning_role view", desc: "View current returning role configuration", badge: "Everyone", type: "public" },
            { name: "/returning_role clear", desc: "Disable the returning role system", badge: "Administrator", type: "perm" }
        ]
    },

    {
        id: "security-antiraid",
        title: "3.0 Security & Anti-Raid",
        icon: "ph-detective",
        tocLabel: "3.0 Security",
        commands: [
            { name: "/antiraid whitelist", desc: "Toggles a role to bypass all detection.", badge: "Administrator", type: "perm" },
            { name: "/antiraid canary", desc: "Toggles Canary mode (Logging Only).", badge: "Administrator", type: "perm" },
            { name: "/antiraid advanced", desc: "Toggles advanced protection tools for this server.", badge: "Administrator", type: "perm" },
            { name: "/antiraid quarantine", desc: "Configure locked quarantine isolation for threat response.", badge: "Administrator", type: "perm" },
            { name: "/antiraid unquarantine", desc: "Restore roles to a quarantined member.", badge: "Administrator", type: "perm" },
            { name: "/antiraid burstlevel", desc: "Set the concurrent active threat tracking limit.", badge: "Administrator", type: "perm" },
            { name: "/antiraid channelsensitivity", desc: "Set a custom threat threshold for a channel.", badge: "Administrator", type: "perm" },
            { name: "/antiraid pause", desc: "Suspends join detection for high-traffic events.", badge: "Administrator", type: "perm" },
            { name: "/antiraid multiplier_channel", desc: "Sets the threat multiplier for a specific channel.", badge: "Administrator", type: "perm" },
            { name: "/antiraid multiplier_role", desc: "Sets the threat multiplier for a specific role.", badge: "Administrator", type: "perm" },
            { name: "/antiraid dashboard", desc: "Displays a comprehensive security overview.", badge: "Administrator", type: "perm" },
            { name: "/antiraid audit", desc: "Scans the server to find where the bot is lacking permissions.", badge: "Administrator", type: "perm" },
            { name: "/antiraid simulate", desc: "Simulates the heat score of a hypothetical message.", badge: "Administrator", type: "perm" },
            { name: "/antiraid threatlist", desc: "Shows users currently carrying high heat scores.", badge: "Administrator", type: "perm" },
            { name: "/antiraid reset", desc: "Hard resets all current scores and threat trackers in the server.", badge: "Administrator", type: "perm" },
            { name: "/antiraid register_scam", desc: "Register scam screenshots as visual blocks.", badge: "Administrator", type: "perm" },
            { name: "/antiraid scam_list", desc: "List blocked visual fingerprints.", badge: "Administrator", type: "perm" },
            { name: "/antiraid unregister_scam", desc: "Remove a blocked visual fingerprint.", badge: "Administrator", type: "perm" },
            { name: "/antiraid logs", desc: "View recent persistent security audit logs.", badge: "Administrator", type: "perm" }
        ]
    },

    {
        id: "staff-tools",
        title: "3.5 Staff Tools",
        icon: "ph-toolbox",
        tocLabel: "3.5 Staff Tools",
        commands: [
            { name: "/brand set", desc: "Set staff tool embed color, footer, or icon URL.", badge: "Manage Server", type: "perm" },
            { name: "/brand view", desc: "View current staff tool response branding.", badge: "Manage Server", type: "perm" },
            { name: "/brand clear", desc: "Clear staff tool response branding.", badge: "Manage Server", type: "perm" },
            { name: "/modpreset set", desc: "Save a reusable moderation reason preset.", badge: "Manage Messages", type: "perm" },
            { name: "/modpreset list", desc: "List saved moderation reason presets.", badge: "Manage Messages", type: "perm" },
            { name: "/modpreset delete", desc: "Delete a saved moderation reason preset.", badge: "Manage Messages", type: "perm" },
            { name: "/modpreset warn", desc: "Warn a member using a saved moderation preset.", badge: "Manage Messages", type: "perm" },
            { name: "/appeal setup", desc: "Enable ban appeals and choose the staff review channel.", badge: "Manage Server", type: "perm" },
            { name: "/appeal disable", desc: "Disable new ban appeal submissions.", badge: "Manage Server", type: "perm" },
            { name: "/appeal submit", desc: "Submit a ban appeal for staff review.", badge: "Everyone", type: "public" },
            { name: "/appeal list", desc: "List recent appeals by status.", badge: "Ban", type: "perm" },
            { name: "/appeal view", desc: "View one appeal by appeal ID.", badge: "Ban", type: "perm" },
            { name: "/appeal close", desc: "Approve or deny a ban appeal.", badge: "Ban", type: "perm" },
            { name: "/suggestion setup", desc: "Choose the staff suggestion board channel.", badge: "Manage Server", type: "perm" },
            { name: "/suggestion submit", desc: "Submit a server suggestion for staff review.", badge: "Everyone", type: "public" },
            { name: "/suggestion list", desc: "List recent suggestions by status.", badge: "Manage Messages", type: "perm" },
            { name: "/suggestion close", desc: "Accept, decline, plan, or close a suggestion.", badge: "Manage Messages", type: "perm" }
        ]
    },

    {
        id: "community-highlights",
        title: "4.0 Community & Highlights",
        icon: "ph-users",
        tocLabel: "4.0 Community",
        commands: [
            { name: "/star info", desc: "View current configuration.", badge: "Everyone", type: "public" },
            { name: "/star set", desc: "Set starboard channel and options", badge: "Manage Server", type: "perm" },
            { name: "/star ignore", desc: "Prevents a channel from being tracked.", badge: "Manage Server", type: "perm" },
            { name: "/star unignore", desc: "Allows a channel to be tracked again.", badge: "Manage Server", type: "perm" },
            { name: "/star stats server", desc: "Starboard stats for this server", badge: "Everyone", type: "public" },
            { name: "/star stats user", desc: "Starboard stats for a user", badge: "Everyone", type: "public" },
            { name: "/star stats top_message", desc: "Most starred message", badge: "Everyone", type: "public" },
            { name: "/autopin toggle", desc: "Turn the entire Auto-Pin system on or off for this server.", badge: "Manage Messages", type: "perm" },
            { name: "/autopin stats", desc: "View live AutoPin system statistics.", badge: "Manage Messages", type: "perm" },
            { name: "/autopin set_threshold", desc: "Set the default required reactions to auto-pin.", badge: "Manage Messages", type: "perm" },
            { name: "/autopin set_emoji", desc: "Set a custom emoji for Auto-Pins.", badge: "Manage Messages", type: "perm" },
            { name: "/autopin channel_override", desc: "Set a custom threshold for a specific channel.", badge: "Manage Messages", type: "perm" },
            { name: "/autopin toggle_channel", desc: "Enable or disable auto-pins in a specific channel.", badge: "Manage Messages", type: "perm" },
            { name: "/autopin settings", desc: "View current auto-pin configurations.", badge: "Manage Messages", type: "perm" },
            { name: "/emoji top_users", desc: "Show who types emojis the most in messages.", badge: "Everyone", type: "public" },
            { name: "/emoji top15", desc: "Show top 15 most used emojis.", badge: "Everyone", type: "public" },
            { name: "/reaction top_users", desc: "Show who reacts the most.", badge: "Everyone", type: "public" },
            { name: "/reaction top15", desc: "Show top 15 most used reactions.", badge: "Everyone", type: "public" },
            { name: "/r toggle", desc: "Enable/disable reply.", badge: "Everyone", type: "public" },
            { name: "/react", desc: "React to a message with an animated emoji.", badge: "Member or Guest", type: "role" },
            { name: "/r set", desc: "Sets reply message if mentioned.", badge: "Member or Guest", type: "role" },
            { name: "/r remove", desc: "Removes your reply.", badge: "Member or Guest", type: "role" },
            { name: "/r_admin_clear", desc: "Clear a users reply.", badge: "Manage Server", type: "perm" }
        ]
    },
    {
        id: "embed-builder",
        title: "4.5 Embed Builder",
        icon: "ph-cards",
        tocLabel: "4.5 Embed Builder",
        commands: [
            { name: "/embed builder", desc: "Open the in-chat embed design workspace.", badge: "Manage Messages", type: "perm" },
            { name: "/embed clone", desc: "Clone a saved template or an existing embed message into the builder.", badge: "Manage Messages", type: "perm" },
            { name: "/embed load", desc: "Post a saved embed template into a selected channel.", badge: "Manage Server", type: "perm" },
            { name: "/embed delete", desc: "Delete a saved embed template after confirmation.", badge: "Manage Server", type: "perm" },
            { name: "/embed disable", desc: "Turn off an active embed automation trigger.", badge: "Manage Server", type: "perm" },
            { name: "/embed list", desc: "View saved embed templates for this server.", badge: "Manage Messages", type: "perm" }
        ]
    },
    {
        id: "events-scheduling",
        title: "5.0 Events & Scheduling",
        icon: "ph-calendar-check",
        tocLabel: "5.0 Events",
        commands: [
            { name: "/raidpoll", desc: "Quickly create Raid Polls", badge: "Manage Channels", type: "perm" },
            { name: "/teamup config", desc: "Customize matching variables, thresholds, and keyword overrides.", badge: "Administrator", type: "perm" },
            { name: "/teamup alias", desc: "Add or remove a dungeon abbreviation.", badge: "Administrator", type: "perm" },
            { name: "/teamup channel", desc: "Set the Team-Up posting channel.", badge: "Administrator", type: "perm" },
            { name: "/teamup role", desc: "Set a role to ping for new Team-Ups.", badge: "Administrator", type: "perm" },
            { name: "/teamup category", desc: "Set the category for team-up countdown channels.", badge: "Administrator", type: "perm" },
            { name: "/teamup quick", desc: "Quickly create a team-up request.", badge: "Everyone", type: "public" },
            { name: "/teamup create", desc: "Open a form to create a team-up.", badge: "Everyone", type: "public" },
            { name: "/teamup list", desc: "List active team-ups in the server.", badge: "Everyone", type: "public" },
            { name: "/teamup edit", desc: "Edit your active team-up request.", badge: "Everyone", type: "public" },
            { name: "/teamup extend", desc: "Add more time to your active team-up.", badge: "Everyone", type: "public" },
            { name: "/teamup transfer-host", desc: "Transfer leadership of your team-up.", badge: "Everyone", type: "public" },
            { name: "/teamup notify", desc: "Get a DM reminder before your team-up expires.", badge: "Everyone", type: "public" },
            { name: "/teamup end", desc: "Close your active team-up channel.", badge: "Everyone", type: "public" },
            { name: "/raid start", desc: "Start a new event signup using a form.", badge: "Keymaster", type: "role" },
            { name: "/raid list", desc: "List all current active signups.", badge: "Everyone", type: "public" },
            { name: "/raid my", desc: "List upcoming events you are signed up for.", badge: "Everyone", type: "public" },
            { name: "/raid edit", desc: "Edit an existing raid event.", badge: "Keymaster", type: "role" },
            { name: "/raid cancel", desc: "Cancel an event by message ID.", badge: "Administrator", type: "perm" },
            { name: "/raid lock", desc: "Lock a raid to prevent new signups.", badge: "Administrator", type: "perm" },
            { name: "/raid unlock", desc: "Unlock a raid to allow signups.", badge: "Administrator", type: "perm" },
            { name: "/set_raid_channel", desc: "Set the channel for event signups.", badge: "Administrator", type: "perm" },
            { name: "/event refresh", desc: "Force update all events immediately.", badge: "Manage Channels", type: "perm" },
            { name: "/event cancel", desc: "Cancel event via Message Link/ID.", badge: "Manage Channels", type: "perm" },
            { name: "/event extend", desc: "Extend event duration.", badge: "Manage Channels", type: "perm" },
            { name: "/event config event", desc: "Set the default event voice category.", badge: "Administrator", type: "perm" },
            { name: "/event config poll", desc: "Set the default poll voice category.", badge: "Administrator", type: "perm" },
            { name: "/event config clean", desc: "Permanently delete old event and poll history.", badge: "Administrator", type: "perm" },
            { name: "/create", desc: "Create an event or poll.", badge: "Manage Channels", type: "perm" },
            { name: "/timeping native", desc: "Link a TimePing to a native Discord event.", badge: "Manage Channel", type: "perm" },
            { name: "/timeping my-events", desc: "View all upcoming events you joined.", badge: "Everyone", type: "public" },
            { name: "/timeping server-events", desc: "List all active server events.", badge: "Everyone", type: "public" },
            { name: "/timeping schedule", desc: "Schedule a future ping with optional image and text.", badge: "Manage Channel", type: "perm" },
            { name: "/timeping add", desc: "Attach an event to a message and ping reactors.", badge: "Manage Channel", type: "perm" },
            { name: "/timeping simulate", desc: "Preview exact reminder firing times.", badge: "Everyone", type: "public" },
            { name: "/timeping remove", desc: "Stop watching a message or native event.", badge: "Manage Channel", type: "perm" },
            { name: "/timeping edit", desc: "Open the live edit panel for an event.", badge: "Manage Channel", type: "perm" },
            { name: "/timeping help", desc: "Show all TimePing commands.", badge: "Everyone", type: "public" },
            { name: "/timeping info", desc: "View TimePing statistics and links.", badge: "Everyone", type: "public" },
            { name: "/timeping defaults view", desc: "See current server default configurations.", badge: "Manage Channel", type: "perm" },
            { name: "/timeping defaults set", desc: "Update server-wide defaults.", badge: "Manage Channel", type: "perm" },
            { name: "/timeping templates add", desc: "Add a reusable reminder interval template.", badge: "Manage Channel", type: "perm" },
            { name: "/timeping templates remove", desc: "Remove a reminder interval template.", badge: "Manage Channel", type: "perm" },
            { name: "/timeping templates list", desc: "List saved interval templates.", badge: "Everyone", type: "public" },
            { name: "/timeping auto-watch add", desc: "Auto-watch a specific channel.", badge: "Manage Channel", type: "perm" },
            { name: "/timeping auto-watch remove", desc: "Remove auto-watch.", badge: "Manage Channel", type: "perm" },
            { name: "/timeping auto-watch list", desc: "List watched channels.", badge: "Everyone", type: "public" },
            { name: "/timeping auto-watch settings", desc: "Configure auto watch.", badge: "Manage Channel", type: "perm" },
            { name: "/ping_config authors", desc: "Safety controls for regular message authors.", badge: "Manage Channel", type: "perm" }
        ]
    },

    {
        id: "voice-channels",
        title: "6.0 Voice & Temp Channels",
        icon: "ph-microphone-stage",
        tocLabel: "6.0 Voice",
        commands: [
            { name: "/voice claim", desc: "Take control of a temporary channel if the owner has left.", badge: "Everyone", type: "public" },
            { name: "/voice kick", desc: "Kick a member from your temp channel.", badge: "Everyone", type: "public" },
            { name: "/voice ban", desc: "Ban a member from rejoining your temp channel.", badge: "Everyone", type: "public" },
            { name: "/voice unban", desc: "Unban a member from your temp channel.", badge: "Everyone", type: "public" },
            { name: "/templates save", desc: "Save current settings as a template.", badge: "Everyone", type: "public" },
            { name: "/templates load", desc: "Create a new VC using a saved template.", badge: "Everyone", type: "public" },
            { name: "/templates list", desc: "List templates.", badge: "Everyone", type: "public" },
            { name: "/voice-admin set-create", desc: "Set the Join-to-Create voice channel.", badge: "Administrator", type: "perm" },
            { name: "/voice-admin set-inactivity", desc: "Set inactivity cleanup timer.", badge: "Administrator", type: "perm" },
            { name: "/voice analytics", desc: "Advanced voice channel analytics.", badge: "Manage Server", type: "perm" }
        ]
    },
    {
        id: "federation-networking",
        title: "7.0 Federation & Networking",
        icon: "ph-globe-hemisphere-west",
        tocLabel: "7.0 Federation",
        commands: [
            { name: "/thread network create", desc: "Create a new Thread network.", badge: "Administrator", type: "perm" },
            { name: "/thread network join", desc: "Join a thread network using a token.", badge: "Administrator", type: "perm" },
            { name: "/thread network info", desc: "View current network info.", badge: "Everyone", type: "public" },
            { name: "/thread network dashboard", desc: "View federation health and config dashboard.", badge: "Everyone", type: "public" },
            { name: "/thread network health", desc: "View network health statistics.", badge: "Everyone", type: "public" },
            { name: "/thread network leave", desc: "Leave the current network.", badge: "Administrator", type: "perm" },
            { name: "/thread network kick", desc: "Remove a guild from the network.", badge: "Administrator", type: "perm" },
            { name: "/thread network rotate_token", desc: "Rotate the join token (Owner only).", badge: "Administrator", type: "perm" },
            { name: "/thread network dissolve", desc: "Delete the network (Owner only).", badge: "Administrator", type: "perm" },
            { name: "/thread network config", desc: "Configure network settings (Owner only).", badge: "Administrator", type: "perm" },
            { name: "/thread network requests", desc: "Manage join requests (Owner only).", badge: "Administrator", type: "perm" },
            { name: "/thread network directory", desc: "List discoverable public networks.", badge: "Everyone", type: "public" },
            { name: "/thread network apply", desc: "Request to join a public network.", badge: "Administrator", type: "perm" },
            { name: "/thread network permission", desc: "Set permissions for a member guild.", badge: "Administrator", type: "perm" },
            { name: "/thread network observer", desc: "Set a guild to Observer Mode.", badge: "Administrator", type: "perm" },
            { name: "/thread network role", desc: "Manage user roles in the network.", badge: "Network Admin", type: "role" },
            { name: "/thread network reputation", desc: "View reputation scores for members.", badge: "Everyone", type: "public" },
            { name: "/thread network rotate_secret", desc: "Rotate primary HMAC secret.", badge: "Administrator", type: "perm" },
            { name: "/thread admin debug", desc: "Developer system inspection tools.", badge: "Administrator", type: "perm" },
            { name: "/thread admin set_federated_forum", desc: "Set Forum for federation.", badge: "Manage Server", type: "perm" },
            { name: "/thread admin set_global_tag", desc: "Only federate threads with this Tag.", badge: "Manage Server", type: "perm" },
            { name: "/thread admin unset_global_tag", desc: "Remove global tag requirement.", badge: "Manage Server", type: "perm" },
            { name: "/thread admin set_admin_channel", desc: "Set channel for connection requests.", badge: "Manage Server", type: "perm" },
            { name: "/thread admin metrics", desc: "View global cross-server metrics.", badge: "Administrator", type: "perm" },
            { name: "/thread mod purge", desc: "Purge messages across the federation.", badge: "Manage Messages", type: "perm" },
            { name: "/thread mod ban", desc: "Ban a user from the entire network.", badge: "Manage Server", type: "perm" },
            { name: "/thread mod timeout", desc: "Timeout user across the federation.", badge: "Manage Server", type: "perm" },
            { name: "/thread mod lock", desc: "Lock this thread across the federation.", badge: "Manage Threads", type: "perm" },
            { name: "/thread mod archive", desc: "Archive this thread across the federation.", badge: "Manage Threads", type: "perm" },
            { name: "/relay create", desc: "Create a new channel relay network.", badge: "Administrator", type: "perm" },
            { name: "/relay link", desc: "Link this channel to a relay.", badge: "Administrator", type: "perm" },
            { name: "/relay unlink", desc: "Unlink channel from the relay.", badge: "Administrator", type: "perm" },
            { name: "/identity set", desc: "Set federation identity and optional badge.", badge: "Everyone", type: "public" },
            { name: "/identity view", desc: "View your current identity.", badge: "Everyone", type: "public" },
            { name: "/identity clear", desc: "Clear your custom identity.", badge: "Everyone", type: "public" },
            { name: "/identity connect", desc: "Connect identity via OAuth2.", badge: "Everyone", type: "public" },
            { name: "/identity proof", desc: "Submit verification token.", badge: "Everyone", type: "public" },
            { name: "/identity verify", desc: "Verify user identity (Admin only).", badge: "Administrator", type: "perm" },
            { name: "/identity unverify", desc: "Unverify user identity (Admin only).", badge: "Administrator", type: "perm" }
        ]
    },

    {
        id: "wizard101-toolkit",
        title: "8.0 Wizard101 Toolkit",
        icon: "ph-magic-wand",
        tocLabel: "8.0 W101 Toolkit",
        commands: [
            { name: "/item", desc: "Search for an item in the W101 database", badge: "Everyone", type: "public" },
            { name: "/damage", desc: "Open the Damage Assistant", badge: "Everyone", type: "public" },
            { name: "/spell", desc: "Search for a spell in the W101 database", badge: "Everyone", type: "public" },
            { name: "/value", desc: "Look up trade value of a Treasure Card", badge: "Everyone", type: "public" },
            { name: "/decks browse", desc: "Browse decks in this server.", badge: "Everyone", type: "public" },
            { name: "/decks search", desc: "Search a deck by name or keywords.", badge: "Everyone", type: "public" },
            { name: "/decks share", desc: "DM a user a specific deck.", badge: "Everyone", type: "public" },
            { name: "/decks export", desc: "Export a deck as an image", badge: "Everyone", type: "public" },
            { name: "/decks create", desc: "Create a new deck.", badge: "Keymaster", type: "role" },
            { name: "/deck show", desc: "Display a saved deck or compact share code.", badge: "Everyone", type: "public" },
            { name: "/deck lookup", desc: "Render and inspect a compact deck code.", badge: "Everyone", type: "public" },
            { name: "/statcaps find", desc: "View Wizard101 stat cap by level and school.", badge: "Everyone", type: "public" },
            { name: "/statcaps main", desc: "Generate main-school stat cap image.", badge: "Everyone", type: "public" },
            { name: "/statcaps offschool", desc: "Generate off-school stat cap image.", badge: "Everyone", type: "public" },
            { name: "/bm stats", desc: "View Beastmoon forms spells and stats.", badge: "Everyone", type: "public" },
            { name: "/bm add", desc: "Add or update your Beastmoon forms.", badge: "Everyone", type: "public" },
            { name: "/bm quick_add", desc: "Add or update forms in raw format.", badge: "Everyone", type: "public" },
            { name: "/bm forms_alt", desc: "View Beastmoon forms for your alt.", badge: "Everyone", type: "public" },
            { name: "/bm forms", desc: "View your Beastmoon forms.", badge: "Everyone", type: "public" },
            { name: "/bm check", desc: "Shows your Beastmoon progress.", badge: "Everyone", type: "public" },
            { name: "/bm leaderboard", desc: "Top Beastmoon gamers in server.", badge: "Everyone", type: "public" },
            { name: "/bm user", desc: "View another users Beastmoon forms.", badge: "Everyone", type: "public" },
            { name: "/bm max", desc: "View users with at least Tier 5 forms.", badge: "Everyone", type: "public" },
            { name: "/bm log_channel", desc: "Sets channel for Beastmoon announcements.", badge: "Manage Channel", type: "perm" },
            { name: "/strategy list", desc: "View existing strategies.", badge: "Keymaster", type: "role" },
            { name: "/strategy add", desc: "Create strategy.", badge: "Administrator", type: "perm" },
            { name: "/strategy delete", desc: "Delete a strategy.", badge: "Administrator", type: "perm" },
            { name: "/tapestry list", desc: "List all tapestries.", badge: "Everyone", type: "public" },
            { name: "/tapestry set", desc: "Toggle status of a tapestry.", badge: "Everyone", type: "public" },
            { name: "/bobblehead list", desc: "List all bobbleheads.", badge: "Everyone", type: "public" },
            { name: "/bobblehead set", desc: "Toggle status of a bobblehead.", badge: "Everyone", type: "public" },
            { name: "/wizard channel", desc: "Set wizard post channel.", badge: "Manage Server", type: "perm" },
            { name: "/wizard missing-channel", desc: "Set missing wizard list channel.", badge: "Manage Server", type: "perm" },
            { name: "/wizard check", desc: "DM users missing wizard info.", badge: "Manage Server", type: "perm" },
            { name: "/wizard missing-list", desc: "Post missing wizard info list.", badge: "Manage Server", type: "perm" }
        ]
    }
];
